---
title: "Client Report - Introduction"
subtitle: "Course DS 250"
author: "Yazvinskaya Anastasia"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

### Introduction

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
from palmerpenguins import load_penguins
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Elevator pitch
_In this project, I analyze the Palmer Penguins dataset to explore relationships between penguin species and their physical characteristics. By visualizing and summarizing key features such as flipper length, body mass, and bill dimensions, we aim to uncover trends and patterns that differentiate the species. Through the use of data visualization techniques, this report will provide insights into the characteristics of penguin populations._

```{python}
#| label: project-data
#| code-summary: Read and format project data

# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
penguins = load_penguins()
penguins
```

## T1: Recreate Charts

__Recreate the example charts from PY4DS: CH2 Data Visualization of the textbook.__

_Add details here to answer the question but `NOT` like an assignment Q&A. You need to `write your answers as a consulting solution report`. A Client needs to understand the answer, but also needs to understand the decisions that went into the answer (when applicable)._

_include figures in chunks and discuss your findings in the figure._

- _YOU SHOULD HAVE QUALITY WRITING THAT DESCRIBES YOUR CHARTS AND TABLES._

- _WE HIGHLY RECOMMEND [GRAMMARLY](https://grammarly.com/) TO FIX YOUR SPELLING AND GRAMMAR. WRITING TAKES TIME TO BE CLEAR. SPEND THE TIME TO PRACITCE._ 

- _YOU SHOULD HAVE QUALITY COMMENTS THAT DESCRIBES YOUR CODES. OFTEN CODEERS WORK IN TEAMS AND YOU NEED TO HAVE QUALTIY COMMENTS FOR YOUR TEAM AND YOURSELF. YOU MAY NEED TO REVISIT CODE YOU WROTE OVER A YEAR AGO, AND IF YOU DONT COMMENT IT NOW YOU WONT REMEMBER WHY YOU DID WHAT YOU DID._

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your (
chart =   ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g")) + \
  geom_point(aes(color="species", shape="species")) + \
  geom_smooth(method="lm") + \
  labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)",
        y="Body mass (g)",
        color="Species",
        shape="Species",
    )

chart

```

## Task 2: Recreate the example chart

__Recreate the example chart from PY4DS: CH2 Data Visualization of the textbook.__

- _include figures in chunks and discuss your findings in the figure._

```{python}
#| label: Q1-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here

(
  ggplot(df.head(500), aes(x='displ', y='hwy')) + geom_point()
)
```

## Task 3: Table used to create the above chart

__Include the table created from PY4DS: CH2 Data Visualization used to create the above chart__

- _PROVIDE TABLES THAT HELP ADDRESS THE QUESTIONS AND TASKS (IF APPLICABLE)._

```{python}
#| label: Q1-table
#| code-summary: table example
#| tbl-cap: "table example"
#| tbl-cap-location: top
# Include and execute your code here
mydat = (df.head(1000)
    .groupby('manufacturer')
    .sum()
    .reset_index()
    .tail(10)
    .filter(["manufacturer","displ","cty", "hwy"])
)

display(mydat)

```

## Task 4: Update the _quarto.yml

__Update the _quarto.yml file in course work portfolio:__
__a. update the title to includ your name__
__b. update the site url to your published site url (this will be in the deployment section in GitHub)__
__c. update the repo-url to your GitHub repository url__
__d. update the issue-url to your GitHub issue url (its the same as the repo url but with /issues/new at the end)__
__e. update the page-footer left to include your name__
__f. update the page-footer right href to include your LinkedIn url (optional)__

- _PROVIDE TABLES THAT HELP ADDRESS THE QUESTIONS AND TASKS (IF APPLICABLE)._

```{python}
#| label: Q1-table2
#| code-summary: table example
#| tbl-cap: "table example"
#| tbl-cap-location: top
# Include and execute your code here
mydat = (df.head(1000)
    .groupby('manufacturer')
    .sum()
    .reset_index()
    .tail(10)
    .filter(["manufacturer","displ","cty", "hwy"])
)

display(mydat)

```

## Task 5: Update the resume.qmd 

__Update the resume.qmd file in course work portfolio to include your updated resume using markdown. See P4DS: CH30 Markdown__

- _PROVIDE TABLES THAT HELP ADDRESS THE QUESTIONS AND TASKS (IF APPLICABLE)._

```{python}
#| label: Q1-table3
#| code-summary: table example
#| tbl-cap: "table example"
#| tbl-cap-location: top
# Include and execute your code here
mydat = (df.head(1000)
    .groupby('manufacturer')
    .sum()
    .reset_index()
    .tail(10)
    .filter(["manufacturer","displ","cty", "hwy"])
)

display(mydat)

```




